apiVersion: apps/v1

kind: Deployment

metadata:
    name: backend-deployment
    labels:
        app: mybackend
        type: backend

spec:
    template:
        metadata:
            name: mybackend-pod
            labels:
                app: mybackend
                type: backend

        spec:
            containers:
                - name: my-backend-container
                  image: adamtra/cluster-backend

                  env:
                    - name: REDIS_HOST
                      value: my-redis-service
                    - name: REDIS_PORT
                      value: '6379'
                    - name: WELCOME_MESSAGE
                      valueFrom:
                        configMapKeyRef:
                          name: myapp-config
                          key: WELCOME_MESSAGE
                    - name: PG_PASSWORD
                      valueFrom:
                        secretKeyRef:
                            name: myapp-secret
                            key: PG_PASSWORD
                  envFrom:
                    - configMapRef:
                        name: postgres-config
    replicas: 3
    selector:
        matchLabels:
            type: backend